spring.application.name=auth-service
server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:auth-db}:${DB_PORT:5432}/${DB_NAME:auth}
spring.datasource.username=${DB_USER:auth_user}
spring.datasource.password=${DB_PASSWORD:T0byt081*}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always